Axioms in certicoq:
So far I have added a new Term constructor (TAx : Term -> Term).  The
argument to TAx is the axiom's type, so this is like having a single
undefined value shared by all axioms.  The various evaluators simply
block on this constant.

I've carried this approach through all of L1, L2 and L3.  This should
evaluate the same as Coq.  On Abishek's example

    Axiom feq1 : (fun x:nat => x) = (fun x:nat => x+x-x).

(with fuel-driven weak cbv evaluation) in L1, L2, and L3, the current
version does indeed agree with Coq.

NOTE: My tests (test_wcbvEval.v in directories L1, L2 and L3) compare

- quoting and translation to Ln followed by evaluation in Ln, 
- evaluation (in Coq) followed by quoting and and translation to Ln.

Once a test rig is set up for each language (a few lines of Coq),
examples are tested with [vm_compute; reflexivity].

If we allow axioms to not block evaluation (e.g. if every match with
only one branch always steps), then this easy testing no longer works.

"make"ing the whole project now fails on

File "./L4_deBruijn/L3_to_L4.v", line 46, characters 2-1365:
Error: Non exhaustive pattern-matching: ...

Since L4 doesn't yet have a TAx term constructor.